// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbYXpVKDdX60j7kx3DDhzvg22KRflz7DA',
    appId: '1:543552982852:web:aec553bc62c9c9b1691111',
    messagingSenderId: '543552982852',
    projectId: 'hariyali-10a26',
    authDomain: 'hariyali-10a26.firebaseapp.com',
    databaseURL: 'https://hariyali-10a26-default-rtdb.firebaseio.com',
    storageBucket: 'hariyali-10a26.firebasestorage.app',
    measurementId: 'G-9EPMMT51ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmGRFwJgvMFPIlIWazmDkME68QjKv-0U',
    appId: '1:543552982852:android:b1cafabe021ef9e9691111',
    messagingSenderId: '543552982852',
    projectId: 'hariyali-10a26',
    databaseURL: 'https://hariyali-10a26-default-rtdb.firebaseio.com',
    storageBucket: 'hariyali-10a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONh25oyYiVWnlQSqF6utcBJksfx5m2K4',
    appId: '1:543552982852:ios:daea51959f8a2d2f691111',
    messagingSenderId: '543552982852',
    projectId: 'hariyali-10a26',
    databaseURL: 'https://hariyali-10a26-default-rtdb.firebaseio.com',
    storageBucket: 'hariyali-10a26.firebasestorage.app',
    iosBundleId: 'com.example.hariyaliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONh25oyYiVWnlQSqF6utcBJksfx5m2K4',
    appId: '1:543552982852:ios:daea51959f8a2d2f691111',
    messagingSenderId: '543552982852',
    projectId: 'hariyali-10a26',
    databaseURL: 'https://hariyali-10a26-default-rtdb.firebaseio.com',
    storageBucket: 'hariyali-10a26.firebasestorage.app',
    iosBundleId: 'com.example.hariyaliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbYXpVKDdX60j7kx3DDhzvg22KRflz7DA',
    appId: '1:543552982852:web:b1625886465b701e691111',
    messagingSenderId: '543552982852',
    projectId: 'hariyali-10a26',
    authDomain: 'hariyali-10a26.firebaseapp.com',
    databaseURL: 'https://hariyali-10a26-default-rtdb.firebaseio.com',
    storageBucket: 'hariyali-10a26.firebasestorage.app',
    measurementId: 'G-DF5X9K0C13',
  );

}